universe:
  - A
  - AAPL
  - ABT
  - ACGL
  - ACN
  - ADBE
  - ADI
  - ADM
  - ADP
  - ADSK
  - AEE
  - AEP
  - AES
  - AFL
  - AIG
  - AJG
  - AKAM
  - ALB
  - ALGN
  - ALL
  - AMAT
  - AMD
  - AME
  - AMGN
  - AMT
  - AMZN
  - AOS
  - APA
  - APD
  - APH
  - ARE
  - ATO
  - AVB
  - AVY
  - AXP
  - AZO
  - BA
  - BAC
  - BAX
  - BBY
  - BDX
  - BEN
  - BF.B
  - BG
  - BLK
  - BMY
  - BRK.B
  - BRO
  - BSX
  - BXP
  - C
  - CAH
  - CASY
  - CAT
  - CB
  - CCI
  - CCL
  - CHD
  - CI
  - CINF
  - CL
  - CLX
  - CMCSA
  - CME
  - CMS
  - CNP
  - COF
  - COO
  - COP
  - COST
  - CPRT
  - CPT
  - CRL
  - CSCO
  - CSGP
  - CSX
  - CTAS
  - CTSH
  - CVS
  - CVX
  - D
  - DE
  - DECK
  - DGX
  - DHI
  - DHR
  - DIS
  - DLTR
  - DOV
  - DRI
  - DTE
  - DUK
  - DVA
  - DVN
  - EBAY
  - ECL
  - ED
  - EFX
  - EIX
  - EL
