pub mod app;
pub mod chat;
pub mod command;
pub mod confirm;
pub mod contract;
pub mod controls;
pub mod detail;
pub mod input;
pub mod launcher;
pub mod layout;
pub mod preferences;
pub mod reducer;
pub mod render_plan;
pub mod renderer;
pub mod screens;
pub mod search;
pub mod startup;
pub mod state;
pub mod theme;
pub mod transport;
pub mod ui;
pub mod virtual_table;
pub mod widgets;

pub use contract::{ConsoleSnapshot, Envelope, MessageType, ShellSnapshot};
pub use launcher::GatewayLauncher;
pub use transport::PipeTransport;
